language: scala
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - graphviz
install:
- pip install --user codecov
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
- sbt ++$TRAVIS_SCALA_VERSION validateJVM &&
  sbt ++$TRAVIS_SCALA_VERSION validateJS
after_success:
- codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a22ea519223977cc7fc9
    on_success: change
    on_failure: always
    on_start: false
matrix:
  include:
  - scala: 2.11.12 # Remember to update this in build.sbt, too.
    sudo: required
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    script:
    - sbt ++$TRAVIS_SCALA_VERSION validateJVM &&
      sbt ++$TRAVIS_SCALA_VERSION validateJS &&
      sbt ++$TRAVIS_SCALA_VERSION validateNative
  - scala: 2.13.0-M4 # Remember to update this in build.sbt, too.
    script:
    - sbt ++$TRAVIS_SCALA_VERSION coreJVM/test scalacheckJVM/test scalazJVM/test shapelessJVM/test &&
      sbt ++$TRAVIS_SCALA_VERSION coreJS/test  scalacheckJS/test  scalazJS/test  shapelessJS/test
  - scala: 2.12.6
