language: scala
jdk:
- openjdk8
sudo: false
addons:
  apt:
    packages:
    - graphviz
before_install:
- git fetch --tags
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - language: shell
    script:
    - bash -c 'shopt -s globstar; shellcheck **/*.sh'

  - scala: 2.12.10 # Remember to update this in build.sbt, too.
    install:
    - pip install --user codecov
    script:
    - sbt ++$TRAVIS_SCALA_VERSION validateJVM &&
      sbt ++$TRAVIS_SCALA_VERSION validateJS
    - SCALAJS_VERSION=0.6.32 sbt ++$TRAVIS_SCALA_VERSION clean validateJS
    after_success:
    - codecov

  - scala: 2.13.1 # Remember to update this in build.sbt, too.
    script:
    - sbt ++$TRAVIS_SCALA_VERSION testJVM213 &&
      sbt ++$TRAVIS_SCALA_VERSION testJS213
    - SCALAJS_VERSION=0.6.32 sbt ++$TRAVIS_SCALA_VERSION clean validateJS

  - stage: release
    script:
    - sbt ci-release
    - SCALAJS_VERSION=0.6.32 sbt ci-release

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a22ea519223977cc7fc9
    on_success: change
    on_failure: always
    on_start: never
